program P03AEX02;
uses CRT;
var
a,b,c: integer ;

begin
clrscr;
writeln('digite o primeiro numero: ');
read(a);
if a<b then
	begin
	end
else
	begin
		b:= a;
	end;
writeln('digite o segundo numero: ');
read(a);
if a<b then
	begin
	end
else
	begin
		b:= a;
	end;
writeln('digite o terceiro numero: ');
read(a);
if a<b then
	begin
	end
else
	begin
		b:= a;
	end;
writeln('o menor numero é: ', a, ' e o maior numero é: ', b);
readkey;
end.